//Recommended
export const AGREGAR_MOVIES = 'AGREGAR_MOVIES';
export const AGREGAR_MOVIES_DESCARGAR_EXITO = 'AGREGAR_MOVIES_DESCARGAR_EXITO';
export const AGREGAR_MOVIES_ERROR = 'AGREGAR_MOVIES_ERROR';

//top rated
export const AGREGAR_MOVIES_TOP = 'AGREGAR_MOVIES_TOP';
export const AGREGAR_MOVIES_DESCARGAR_EXITO_TOP =
  'AGREGAR_MOVIES_DESCARGAR_EXITO_TOP';
export const AGREGAR_MOVIES_ERROR_TOP = 'AGREGAR_MOVIES_ERROR_TOP';
