export const AGREGAR_MOVIES = 'AGREGAR_MOVIES';
export const AGREGAR_MOVIES_EXITO = 'AGREGAR_MOVIES_EXITO';
export const AGREGAR_MOVIES_DESCARGAR_EXITO = 'AGREGAR_MOVIES_DESCARGAR_EXITO';
export const AGREGAR_MOVIES_ERROR = 'AGREGAR_MOVIES_ERROR';

